baseurl = "https://notes.corre.bio"
languageCode = "en-us"
author = "Ewen Corre"
title = "Ewen's thoughts"
theme = "hugo-tanka"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 8
[[menu.main]]
    name = "Main blog →"
    url = "https://ewen.corre.bio"
    weight = 10

[params]
    sitename = "Ewen's thoughts"
    description = "A collection of Ewen's thoughts"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"


